language: python
dist: xenial
sudo: required

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

addons:
  apt:
    packages:
      - espeak
      - mbrola
      - mbrola-fr1
      - mbrola-fr4
      - mbrola-en1
      - mbrola-de4

script:
  - python setup.py test
